version: "3.9"

#NETWORK
networks:
  web-network:
    driver: bridge

services:
  # container webserver
  web:
    container_name: webserver
    build:
      dockerfile: ./docker/dockerfile/webserver.dockerfile
      context: .
    hostname: web
    restart: always
    networks:
      - web-network
    volumes:
      - .:/var/www/html/hr_management_system
      - ./docker/config/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "9999:80"
      - "4488:443"
    links:
      - mysql
  queue:
    container_name: webqueue
    build:
      dockerfile: ./docker/dockerfile/webserver.dockerfile
      context: .
    restart: always
    networks:
      - web-network
    volumes:
      - .:/var/www/html/hr_management_system
      - ./docker/config/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    command: php artisan queue:work --queue=high,default
    links:
      - mysql
  # container db
  mysql:
    container_name: db
    image: mysql:latest
    hostname: mysql
    restart: always
    networks:
      - web-network
    volumes:
      - ./docker/mysql/db/:/var/lib/mysql
      - ./docker/config/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root@123
      - MYSQL_DATABASE=hr_management_system
      - MYSQL_USER=member
      - MYSQL_PASSWORD=member@123
    ports:
      - "3333:3306"
